version: "3"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile_base
    container_name: codingexercise_base
  
  http:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: http
    environment:
      ENV: 'development'
    volumes:
      - /tmp/http:/services/http/log
    links:
      - postgres
    ports:
      - "5050:5050"
    networks:
      - default

  postgres:
    image: postgres:11.7-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge
